---
- become: true
  gather_facts: false
  handlers:
  - ansible.builtin.command:
      cmd: vault secrets enable -path=kv kv
    changed_when: true
    environment:
      VAULT_ADDR: http://localhost:8200
      VAULT_TOKEN: '{{ vault_root_token }}'
    name: Enable KV secrets engine
  - ansible.builtin.command:
      cmd: vault kv put kv/my-secret my-value=s3cr3t
    changed_when: true
    environment:
      VAULT_ADDR: http://localhost:8200
      VAULT_TOKEN: '{{ vault_root_token }}'
    name: Write a secret to the KV secrets engine
  - ansible.builtin.command:
      cmd: vault kv get kv/my-secret
    changed_when: true
    environment:
      VAULT_ADDR: http://localhost:8200
      VAULT_TOKEN: '{{ vault_root_token }}'
    name: Read the secret from the KV secrets engine
    register: vault_secret
  - ansible.builtin.assert:
      quiet: true
      that:
      - vault_secret.stdout.find('s3cr3t') != -1
    name: Check if the read secret is correct
  hosts: all
  name: Verify
  tasks:
  - ansible.builtin.command:
      cmd: vault --version
    changed_when: false
    name: Try vault --version
  - ansible.builtin.service:
      name: vault
      state: stopped
    name: Stop vault service
  - ansible.builtin.command:
      cmd: vault server -dev -dev-root-token-id="{{ vault_root_token }}"
    async: 180
    changed_when: true
    name: Start vault server (dev)
    notify:
    - Enable KV secrets engine
    - Write a secret to the KV secrets engine
    - Read the secret from the KV secrets engine
    - Check if the read secret is correct
    poll: 0
  vars:
    vault_root_token: root
